# batch_size: 4
# iters: 160000
batch_size: 8
iters: 80000

train_dataset:
  type: Dataset
  dataset_root: data/custom
  num_classes: 5
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomRotation
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    # - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: RandomBlur
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train
  train_path: data/custom/train.txt

val_dataset:
  type: Dataset
  num_classes: 5 
  dataset_root: data/custom
  transforms:
    - type: Normalize
  mode: val
  val_path: data/custom/val.txt


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8,0.2]
  coef: [1]


model:
  type: FCN
  backbone:
    type: HRNet_W18
    align_corners: False
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  num_classes: 5
  pretrained: Null
  backbone_indices: [-1]



