_base_: '../_base_/cityscapes.yml'

batch_size: 2
iters: 160000

train_dataset:
  type: Dataset
  dataset_root: data/custom
  num_classes: 5
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    # - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: RandomBlur
    - type: RandomDistort
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: Normalize
  mode: train
  train_path: data/custom/train.txt

val_dataset:
  type: Dataset
  num_classes: 5
  dataset_root: data/custom
  transforms:
    - type: Normalize
  mode: val
  val_path: data/custom/val.txt

model:
  type: SegFormer_B2
  num_classes: 5
  pretrained: https://bj.bcebos.com/paddleseg/dygraph/mix_vision_transformer_b2.tar.gz

optimizer:
  _inherited_: False
  type: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.00006
  power: 1

# loss:
#   types:
#     - type: CrossEntropyLoss
#   coef: [1]
loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
          # weight: [0.3,0.3,0.3,0.1]
        - type: LovaszSoftmaxLoss
      coef: [0.8,0.2]
  coef: [1]
